plugins {
	id 'fabric-loom' version "${loom_version}"
	id 'maven-publish'
    id "me.modmuss50.mod-publish-plugin" version "1.1.0"
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven { url "https://maven.shedaniel.me" }
	maven {
		url 'https://maven.blamejared.com'
	}
	maven {
		url "https://www.cursemaven.com"
		content {
			includeGroup "curse.maven"
		}
	}
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        url = "https://repo.repsy.io/coolerpromc/maven"
    }
}

fabricApi {
	configureDataGeneration {
		client = true
	}
}

loom {
    accessWidenerPath = file("src/main/resources/fletchingrecipe.classtweaker");
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    modImplementation include("com.electronwill.night-config:core:3.8.1")
    modImplementation include("com.electronwill.night-config:toml:3.8.1")

    modCompileOnly("mezz.jei:jei-${minecraft_version}-fabric-api:${jei_version}")
    modRuntimeOnly("mezz.jei:jei-${minecraft_version}-fabric:${jei_version}")

	modCompileOnly "me.shedaniel:RoughlyEnoughItems-api-fabric:${rei_version}"
	modCompileOnly "me.shedaniel:RoughlyEnoughItems-fabric:${rei_version}"

    modCompileOnly "maven.modrinth:more-fletching-tables:1.8.3-fabric,1.21.11"
    modCompileOnly "com.coolerpromc:arrowplus:3.1.0+1.21.11-fabric"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

// configure the maven publication
publishing {
    publications {
        register('mavenJava', MavenPublication) {
            groupId = groupId
            artifactId = archives_base_name
            version = mod_version
            from components.java
        }
    }
    repositories {
        mavenLocal()
        maven {
            url = findProperty("repsy_url")
            credentials {
                username = findProperty("repsy_username")
                password = findProperty("repsy_password")
            }
        }
    }
}

publishMods {
    file.set(remapJar.archiveFile)
    type = STABLE
    modLoaders.add("fabric")
    changelog = file("changelog.md").text
    displayName = "fletchingrecipe-" + mod_version

    curseforge {
        projectId = "1364606"
        accessToken = findProperty("CF_TOKEN")
        minecraftVersions.add(minecraft_version)
    }

    modrinth {
        projectId = 'nDfK7W8j'
        accessToken = findProperty("MODRINTH_TOKEN")
        minecraftVersions.add(minecraft_version)
    }
}