org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1-snapshot-7
minecraft_version_range=[26.1-snapshot-7,)
neo_version=26.1.0.0-alpha.12+snapshot-7
neo_version_range=[26.1.0.0-alpha.12+snapshot-7,)
loader_version_range=[4,)

jei_version=28.5.0.13

architectury_version=18.0.3
cloth_config_version=20.0.148
rei_version=20.0.810

## Mod Properties
mod_id=fletchingrecipe
mod_name=FletchingRecipe
mod_license=All Rights Reserved
mod_version=1.2.0+26.1-snapshot-7-neoforge
mod_group_id=com.coolerpromc
mod_authors=CoolerProMC
mod_description=
