org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20
minecraft_version=1.21.11
minecraft_version_range=[1.21.11]
neo_version=21.11.24-beta

jei_version=27.4.0.15

architectury_version=18.0.3
cloth_config_version=20.0.148
rei_version=20.0.810

## Mod Properties
mod_id=fletchingrecipe
mod_name=FletchingRecipe
mod_license=All Rights Reserved
mod_version=1.2.1+1.21.11-neoforge
mod_group_id=com.coolerpromc
mod_authors=CoolerProMC
mod_description=
