# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1-snapshot-10
loader_version=0.18.4
loom_version=1.14-SNAPSHOT

rei_version=20.0.810

# Mod Properties
mod_version=1.2.1+26.1-snapshot-10-fabric
maven_group=com.coolerpromc
archives_base_name=fletchingrecipe

# Dependencies
fabric_version=0.143.6+26.1
jei_version=28.5.0.13